micronaut:
  application:
    name: mercadoLivreKotlin
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/mercadoLivreKotlin
    driverClassName: org.postgresql.Driver
    username: postgres
    password: zupper
    dialect: POSTGRES

jpa.default.properties.hibernate.hbm2ddl.auto: update